[project]
name = "django-template"
version = "0.1.0"
description = "A Django project template"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Matus Kocik", email = "matuskocik@gmail.com" }
]
license = "MIT"
dependencies = [
    "django>=5.1.5,<6.0.0",
    "python-decouple>=3.8",
    "psycopg[binary]>=2.9.10"
]

[dependency-groups]
dev = [
    "pip-tools>=6.12.3",
    "black>=24.10.0",
    "isort>=5.13.2",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-django>=4.9.0",
    "ruff>=0.9.2"
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["I"]
